### PR TITLE
Add chromeapp input variable

### PR DESCRIPTION
**Pull request by MickaelFontes**
- Add chromeapp variable for chrome binaries with different names on Linux and MacOS.
- Fix build command for ncc
- Fix default package name (wrong name for `dpkg` lookup by default on ubuntu runners)
Closes nanasess/setup-chromedriver#252

### CODE REVIEW

**Comment by nanasess** [comment]
Thanks for your contribution!
I will merge when I have Windows support as well.💪

**Comment by MickaelFontes** [comment]
Hey @nanasess  my pleasure!  I also noticed some random issues on the ci with the MacOS14 runners (maybe xvfb did not have enough time to start properly?)
Ok noted for the merge, you want to add it yourself for the PowerShell/Windows part?

**Comment by nanasess** [comment]
@MickaelFontes 
Sorry for the delay in getting back to you due to a cold.
@MickaelFontes san, can you also handle PowerShell/Windows part?

**Comment by nanasess** [comment]
LGTM

**Pull request merged**
