### PR TITLE
Use @puppeteer/browsers to install chromedriver

### PR DESCRIPTION
**Pull request by mvdbeek**
I've only performed the most basic of checks ... you can see it in action here: https://github.com/galaxyproject/galaxy/actions/runs/5667235238/job/15355686453?pr=16461#step:10:1

### CODE REVIEW

**Comment by mvdbeek** [comment]
Fair enough. I suppose just installing npx if it's not available is also not an option ?

**Comment by nanasess** [comment]
@mvdbeek We want to minimize dependencies.🙇‍♂️

**Comment by mvdbeek** [comment]
Thanks, that makes sense.

**Comment by nanasess** [comment]
@mvdbeek 
We will never forget your contribution.🙏
Pull Request Thank you so much!

**Pull request closed without merging**
